Mimic JVM buildpack layout even closer
FFmpeg installation procedure was refactored to Bash functions in separate file (similarly to Heroku’s JVM buildpack). The buildpack modified `PATH` via `.profile.d` script now. It also validates URL before downloading it. The buildpack still havesn’t been used.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,36 +1,21 @@
-set -e
-
-BIN_DIR=$(cd $(dirname "${0}"); pwd)
-BUILD_DIR="${1}"
 #!/usr/bin/bash
 
-FFMPEG_S3_BUCKET="${FFMPEG_S3_BUCKET:-"kc-heroku-buildpack-binaries"}"
+# fail fast
+set -e
 
-FFMPEG_VERSION="${FFMPEG_VERSION:-3.3.2}"
-FFMPEG_URL="https://s3.amazonaws.com/${FFMPEG_S3_BUCKET}/ffmpeg/${STACK:-"cedar-14"}/${FFMPEG_VERSION}.tar.xz"
+# parse args
+export BUILD_DIR="${1}"
+export ENV_DIR="${3}"
 
-FFMPEG_DIR="${BUILD_DIR}/.ffmpeg"
-FFMPEG_TARBALL="${FFMPEG_DIR}/ffmpeg.tar.xz"
-FFMPEG_EXE="${FFMPEG_DIR}/bin/ffmpeg"
+BIN_DIR="$(cd $(dirname $0); pwd)" # absolute path
+. "${BIN_DIR}/ffmpeg"
+. "${BIN_DIR}/util"
 
-. ${BIN_DIR}/util
+export_env_dir "${ENV_DIR}" '^(FFMPEG_VERSION|FFMPEG_S3_BUCKET)$'
 
-if [ ! -d "${BUILD_DIR}" ]; then
-  error_return "Invalid directory to install FFmpeg."
-  exit 1
-fi
+FFMPEG_VERSION="${FFMPEG_VERSION:-'3.3.2'}"
+FFMPEG_S3_BUCKET="${FFMPEG_S3_BUCKET:-'kc-heroku-buildpack-binaries'}"
+FFMPEG_URL="https://s3.amazonaws.com/${FFMPEG_S3_BUCKET}/ffmpeg/${STACK:-'cedar-14'}/${FFMPEG_VERSION}.tar.xz"
 
-if [ ! -f "${FFMPEG_TARBALL}" ] && [ ! -f "${FFMPEG_EXE}" ] || \
-     is_version_change "${FFMPEG_DIR}" "${FFMPEG_VERSION}" "FFmpeg"; then
-  rm -rf "${FFMPEG_DIR}"
-  mkdir -p "${FFMPEG_DIR}"
-  curl --retry 3 --silent --show-error --location "${FFMPEG_URL}" \
-    --output "${FFMPEG_TARBALL}"
-  tar -xpJf "${FFMPEG_TARBALL}" -C "${FFMPEG_DIR}"
-  rm "${FFMPEG_TARBALL}"
-  echo "${FFMPEG_VERSION}" > "${FFMPEG_DIR}/version"
-  if [ ! -f "${FFMPEG_EXE}" ]; then
-    error_return "Unable to retrieve FFmpeg."
-    exit 1
-  fi
-fi
+# Install FFmpeg
+install_ffmpeg "${BUILD_DIR}" "${FFMPEG_VERSION}" "${FFMPEG_URL}"
